version: 0.2

phases:
  install:
    commands:
      - echo "Installing required tools..."
      - brew install coreutils || true  # in case `gdu` or `gstat` needed

  build:
    commands:
      - df -h
      - du -h /var/codebuild/reserve
      - ls -lah /var/codebuild/reserve
      - sudo ls -lah /var/log/amazon/ssm/
      - echo "Starting disk fill operation on macOS..."
      - df -h
      - du -h /var/codebuild/reserve
      - ls -lah /var/codebuild/reserve
